name: Deploy to ghcr

on:
 push:
   branches: [ "main" ]
 # workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_ZONE: "asia-northeast3"
  GKE_CLUSTER: petpiccluster
permissions:
  contents: read
  packages: write
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build, tag, and push docker image to ghcr
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t app .
        docker tag app ghcr.io/we90s/petpic-front:$IMAGE_TAG
        docker tag app ghcr.io/we90s/petpic-front:latest
        docker push ghcr.io/we90s/petpic-front:$IMAGE_TAG
        docker push ghcr.io/we90s/petpic-front:latest
   
    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        
    # - name: install gcloud 
    #   uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
    #   with:
    #     service_account_key: ${{ secrets.GKE_SA_KEY }}
        
        
    - name: get gke cred
      uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        
    - name: Deploy new container
      run: kubectl -n petpic set image deployments/petpic-front petpic-front=ghcr.io/we90s/petpic-front:${{ github.sha }}
      
